version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - echo "dependencies install completed `date`"
  build:
    commands:
      - cd src
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file template.yml --s3-bucket icar-deploy --output-template-file packaged.yml
      - aws cloudformation deploy --template-file packaged.yml --stack-name icar-serverless --capabilities CAPABILITY_IAM  
  post_build:
    commands:
      - echo "build completed on `date`"
