version: '3.1'

services:
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment: 
      - MYSQL_DATABASE=icar3
      - MYSQL_ROOT_PASSWORD=icarpassword
  dynamodb:
    image: cnadiminti/dynamodb-local
    ports:
      - "8000:8000"
networks:
  default:
    external:
      name: icar-network