AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.


Resources: 
  Login:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "core-login"
      Handler: src/core/auth/login.handler
      Role: arn:aws:iam::553211419435:role/icarlambda
      Runtime: nodejs6.10
      Events:
        Login:
          Type: Api
          Properties:  
            Path: /login
            Method: post
  Logout:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "core-logout"
      Handler: src/core/auth/logout.handler
      Role: arn:aws:iam::553211419435:role/icarlambda
      Runtime: nodejs6.10
      Events:
        Login:
          Type: Api
          Properties:  
            Path: /logout
            Method: post
  ClientCreate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "core-create"
      Handler: src/core/client/create.handler
      Role: arn:aws:iam::553211419435:role/icarlambda
      Runtime: nodejs6.10
      Timeout: 300
      Events:
        ClientCreate:
          Type: Api
          Properties:
            Path: /client
            Method: post
  