AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ICar Sample Serverless Application.

Resources:

  LoginApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.login
      Runtime: nodejs6.10
      CodeUri: ./src/auth
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
  LogoutApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.logout
      Runtime: nodejs6.10
      CodeUri: ./src/auth
      Events:
        Logout:
          Type: Api
          Properties:
            Path: /logout
            Method: post
